import { CardName } from 'domain/card-name'
import allianceFrigate from '../../resources/cards/cards/Alliance Frigate.png'
import acceptableLosses from '../../resources/cards/gambits/Acceptable Losses.png'
import adimarRasmusson from '../../resources/cards/heroes/Admiral Rasmussen.png'
import agingBattleship from '../../resources/cards/cards/Aging Battleship.png'
import alignmentBot from '../../resources/cards/cards/Alignment Bot.png'

export const cardImages: Record<CardName, string> = {
    'Acceptable Losses': acceptableLosses,
    'Administrator Tung': '',
    'Admiral Rasmusson': adimarRasmusson,
    'Aging Battleship': agingBattleship,
    'Alignment Bot': alignmentBot,
    'Alliance Frigate': allianceFrigate,
    'Alliance Landing': '',
    'Alliance Transport': '',
    'Alpha Max': '',
    'Assault Pod': '',
    'Assault Shard': '',
    'Assur 4': '',
    'Asteroid Mining': '',
    'Barter World': '',
    'Battle Barge': '',
    'Battle Blob': '',
    'Battle Bot': '',
    'Battle Mech': '',
    'Battle Pod': '',
    'Battle Screecher': '',
    'Battle Star': '',
    'Battle Station': '',
    'Bio-Captain Kalle': '',
    'Bio-Warrior Storm': '',
    'Biodroid Otto': '',
    'Bioform Freeman': '',
    'Black Hole': '',
    'Black Market': '',
    'Blob Alpha': '',
    'Blob Bot': '',
    'Blob Builder': '',
    'Blob Carrier': '',
    'Blob Destroyer': '',
    'Blob Fighter': '',
    'Blob Miner': '',
    'Blob Overlord': '',
    'Blob Wheel': '',
    'Blob World': '',
    'Blockade Runner': '',
    'Bold Raid': '',
    'Border Fort': '',
    'Border Skirmish': '',
    'Bounty Hunter': '',
    'Brain World': '',
    'Breeding Site': '',
    'Builder Bot': '',
    'Buyer’s Market': '',
    'CEO Shaner': '',
    'CEO Torres': '',
    'Capitol World': '',
    'Captured Outpost': '',
    'Cargo Barge': '',
    'Cargo Boat': '',
    'Cargo Craft': '',
    'Cargo Launch': '',
    'Cargo Mech': '',
    'Cargo Pod': '',
    'Cargo Raptor': '',
    'Cargo Rocket': '',
    'Central Office': '',
    'Central Station': '',
    'Chairman Haygan': '',
    'Chancellor Hartman': '',
    'Cluster Scout': '',
    'Cluster Viper': '',
    'Coalition Fortress': '',
    'Coalition Freighter': '',
    'Coalition Messenger': '',
    'Colony Seed Ship': '',
    'Command Center': '',
    'Command Cruiser': '',
    'Command Shard': '',
    'Command Ship': '',
    'Commander Klik': '',
    'Commitment to the Cause': '',
    'Commodore Zhang': '',
    'Confessor Morris': '',
    'Construction Hauler': '',
    'Conversion Yard': '',
    'Convoy Bot': '',
    'Cunning Captain': '',
    'Customs Frigate': '',
    'Data Priest Kaufman': '',
    'Death World': '',
    'Defense Bot': '',
    'Defense Center': '',
    'Defense System': '',
    'Defy the Empire | Rules (Defy the Empire)': '',
    'Destroyer Bot': '',
    'Dimensional Horror | Rules (Dimensional Horror)': '',
    'Diplomatic Shuttle': '',
    'Doctor Clark': '',
    'Early Recruitment': '',
    'Embassy Base': '',
    'Embassy Transport': '',
    'Embassy Yacht': '',
    'Emergency Repairs': '',
    'Emperor\'s Dreadnaught': '',
    'Energy Shield': '',
    'Enforcer Mech': '',
    'Entrenched Loyalties': '',
    'Escort Viper': '',
    'Exchange Point': '',
    'Factory World': '',
    'Farm Ship': '',
    'Federal Transport': '',
    'Federation Battleship': '',
    'Federation Cruiser': '',
    'Federation Scout': '',
    'Federation Shipyard': '',
    'Federation Shuttle': '',
    'Fighter Base': '',
    'Fighter Pod': '',
    'Flare Mining': '',
    'Fleet HQ': '',
    'Fleeting Opportunities': '',
    'Fortress Oblivion': '',
    'Frantic Preparations': '',
    'Freight Hauler': '',
    'Freight Raft': '',
    'Frontier Expedition': '',
    'Frontier Ferry': '',
    'Frontier Fleet': '',
    'Frontier Hawk': '',
    'Frontier Runner': '',
    'Frontier Station': '',
    'Frontier Tug': '',
    'Fusion Bot': '',
    'Galactic Summit': '',
    'Heavy Cruiser': '',
    'Hidden Base': '',
    'High Admiral Jochum | Rules (Splinter Abilities)': '',
    'High Admiral Shaner': '',
    'High Priest Lyle': '',
    'Hive Lord': '',
    'Hive Queen': '',
    'Imperial Defender': '',
    'Imperial Fighter': '',
    'Imperial Flagship': '',
    'Imperial Frigate': '',
    'Imperial Palace': '',
    'Imperial Scout': '',
    'Imperial Smuggler': '',
    'Imperial Talon': '',
    'Imperial Trader': '',
    'Imperial Viper': '',
    'Industrial Upgrade': '',
    'Infested Moon': '',
    'Integration Port': '',
    'Ion Station': '',
    'Jamming Terminal': '',
    'Laser Drone': '',
    'Light Cruiser': '',
    'Long Hauler': '',
    'Lookout Post': '',
    'Lost Dreadnaught': '',
    'Loyal Colony': '',
    'Lunar Landing': '',
    'Machine Base': '',
    'Maximum Warp': '',
    'Mech Battleship': '',
    'Mech Command Ship': '',
    'Mech Cruiser': '',
    'Mech Fortress': '',
    'Mech World': '',
    'Mech Wurm': '',
    'Mega Mech': '',
    'Merc Battlecruiser': '',
    'Merc Cruiser': '',
    'Mercenary Garrison': '',
    'Midgate Station': '',
    'Mining Mech': '',
    'Missile Bot': '',
    'Missile Launcher': '',
    'Missile Mech': '',
    'Missile Silo': '',
    'Mobile Market': '',
    'Moonwurm Hatchling': '',
    'Mutant Drone | Pod Token': '',
    'Nanobot Swarm': '',
    'Naval Yard': '',
    'Needle Lancer': '',
    'Nemesis Beast | Rules (Nemesis Beast)': '',
    'Nesting Ground': '',
    'Neural Nexus': '',
    'Operations Center': '',
    'Operations Platform': '',
    'Orbital Crane': '',
    'Orbital Gun Platform': '',
    'Orbital Platform': '',
    'Orbital Shuttle': '',
    'Outland Station': '',
    'Pact Manager Scott': '',
    'Pact Pod': '',
    'Pact Searcher Sheldon': '',
    'Pact Warship': '',
    'Parks Station': '',
    'Patience Rewarded': '',
    'Patrol Boat': '',
    'Patrol Bot': '',
    'Patrol Cutter ': '',
    'Patrol Mech': '',
    'Picking Sides': '',
    'Plague Pod': '',
    'Plasma Bot': '',
    'Plasma Vent': '',
    'Political Maneuver': '',
    'Port Cutter': '',
    'Port of Call': '',
    'Powerful Backing': '',
    'Probe Bot': '',
    'Prolonged Conflict': '',
    'Ram Pilot': '',
    'Rapid Construction': '',
    'Rapid Deployment': '',
    'Ready Reserves': '',
    'Reclamation Station': '',
    'Recon Mission': '',
    'Recon Shard': '',
    'Recovery Mech': '',
    'Recruiting Drive': '',
    'Recycle Bot': '',
    'Recycling Station': '',
    'Repair Bot': '',
    'Repair Mech': '',
    'Rise to Power': '',
    'Royal Redoubt': '',
    'Rushed Defenses': '',
    'Ruthless Efficiency': '',
    'Salvage Drone': '',
    'Salvage Operation': '',
    'Salvage Shard': '',
    'Sapphire City Base': '',
    'Scavenger Bot': '',
    'Scout Bot': '',
    'Scrap Factory': '',
    'Secret Outpost': '',
    'Security Craft': '',
    'Siege Fortress': '',
    'Smuggling Run': '',
    'Solar Skiff': '',
    'Space Station': '',
    'Spawning Wurm': '',
    'Special Ops Director': '',
    'Spike Cluster': '',
    'Spike Colony': '',
    'Spike Pod': '',
    'Star Barge': '',
    'Star Fortress': '',
    'Starbase Omega': '',
    'Stealth Needle': '',
    'Stealth Tower': '',
    'Stellar Falcon': '',
    'Stellar Link': '',
    'Stellar Ray': '',
    'Stellar Reef': '',
    'Storage Silo': '',
    'Strategist Thompson': '',
    'Summit Site': '',
    'Super Carrier': '',
    'Super Freighter': '',
    'Supply Bot': '',
    'Supply Depot': '',
    'Supply Run': '',
    'Surprise Assault': '',
    'Survey Ship': '',
    'Swarm Cell': '',
    'Swarm Cluster': '',
    'Swarm Colony': '',
    'Swarming Point': '',
    'Tactical Maneuver': '',
    'Tanker Mech': '',
    'Templar Brehmer': '',
    'Temple Guardian': '',
    'The Ark': '',
    'The Armory': '',
    'The Citadel': '',
    'The Colossus': '',
    'The Hive': '',
    'The Incinerator': '',
    'The Oracle': '',
    'The Wrecker': '',
    'Total War': '',
    'Tractor Beam': '',
    'Trade Bot': '',
    'Trade Envoy': '',
    'Trade Escort': '',
    'Trade Hauler': '',
    'Trade Hive': '',
    'Trade Mission': '',
    'Trade Pod': '',
    'Trade Raft': '',
    'Trade Star': '',
    'Trade Wheel': '',
    'Trading Colony': '',
    'Trading Post': '',
    'Transit Nexus': '',
    'Transport Shard': '',
    'Tribute Transport': '',
    'Triumphant Return': '',
    'Two-Pronged Attack': '',
    'Union Cluster': '',
    'Union Stronghold': '',
    'Unity Fighter': '',
    'Unity Station': '',
    'Unity Warcraft | Rules (Part 2 of 3)': '',
    'Unlikely Alliance': '',
    'Valken’s Enterprise | Coalition Stronghold': '',
    'Veteran Pilots': '',
    'Viper Bot': '',
    'War Elder': '',
    'War Kite': '',
    'War Mech': '',
    'War World': '',
    'Warning Beacon': '',
    'Warp Jump': '',
    'Warpgate Cruiser': '',
    'Warpgate Nexus': '',
    'Warrior Drone | Pod Token': '',
    'Warrior Pod': '',
    'Welder Drone': '',
    'Wild Gambit': '',
    'Worker Drone | Pod Token': '',
    'Young Queen | Pod Token': '',
    Ally: '',
    Arcadia: '',
    Armada: '',
    Arsenal: '',
    Assimilator: '',
    Battlecruiser: '',
    Bioformer: '',
    Bombardment: '',
    Brooder: '',
    Burrower: '',
    Colonize: '',
    Comet: '',
    Convert: '',
    Converter: '',
    Corsair: '',
    Corvette: '',
    Crusher: '',
    Cutter: '',
    Defend: '',
    Demolisher: '',
    Diversify: '',
    Dominate: '',
    Dreadnaught: '',
    Exploration: '',
    Explorer: '',
    Exterminate: '',
    Falcon: '',
    Flagship: '',
    Freighter: '',
    Gateship: '',
    Guidance: '',
    Gunship: '',
    Hammerhead: '',
    Hellfire: '',
    Influence: '',
    Junkyard: '',
    Knightstar: '',
    Lancer: '',
    Laser: '',
    Leviathan: '',
    Megahauler: '',
    Meganaut: '',
    Mobilization: '',
    Monopolize: '',
    Moonwurm: '',
    Mothership: '',
    Obliterator: '',
    Parasite: '',
    Peacekeeper: '',
    Predator: '',
    Processing: '',
    Protopod: '',
    Pulverizer: '',
    Quasar: '',
    Ram: '',
    Ranger: '',
    Ravager: '',
    Ripper: '',
    Rule: '',
    Scout: '',
    Screecher: '',
    Sentinel: '',
    Shield: '',
    Starmarket: '',
    Stealth: '',
    Stinger: '',
    Superflare: '',
    Supernova: '',
    Swarmer: '',
    Swarmling: '',
    Unite: '',
    Viper: '',
    Voyager: '',
    Warp: '',
    Wormhole: ''
}
