import { CardName } from 'domain/card-name'
import barterWorld from '../../resources/cards/barter-world.jpg'
import battleBlob from '../../resources/cards/battle-blob.jpg'
import battleMech from '../../resources/cards/battle-mech.jpg'
import battlePod from '../../resources/cards/battle-pod.jpg'
import battleStation from '../../resources/cards/battle-station.jpg'
import battlecruiser from '../../resources/cards/battlecruiser.jpg'
import blobCarrier from '../../resources/cards/blob-carrier.jpg'
import blobDestroyer from '../../resources/cards/blob-destroyer.jpg'
import blobFighter from '../../resources/cards/blob-fighter.jpg'
import blobWheel from '../../resources/cards/blob-wheel.jpg'
import blobWorld from '../../resources/cards/blob-world.jpg'
import brainWorld from '../../resources/cards/brain-world.jpg'
import centralOffice from '../../resources/cards/central-office.jpg'
import commandShip from '../../resources/cards/command-ship.jpg'
import corvette from '../../resources/cards/corvette.jpg'
import cutter from '../../resources/cards/cutter.jpg'
import defenseCenter from '../../resources/cards/defense-center.jpg'
import dreadnaught from '../../resources/cards/dreadnaught.jpg'
import embassyYacht from '../../resources/cards/embassy-yacht.jpg'
import explorer from '../../resources/cards/explorer.jpg'
import federationShuttle from '../../resources/cards/federation-shuttle.jpg'
import flagship from '../../resources/cards/flagship.jpg'
import fleetHq from '../../resources/cards/fleet-hq.jpg'
import freighter from '../../resources/cards/freighter.jpg'
import imperialFighter from '../../resources/cards/imperial-fighter.jpg'
import imperialFrigate from '../../resources/cards/imperial-frigate.jpg'
import junkyard from '../../resources/cards/junkyard.jpg'
import machineBase from '../../resources/cards/machine-base.jpg'
import mechWorld from '../../resources/cards/mech-world.jpg'
import missileBot from '../../resources/cards/missile-bot.jpg'
import missileMech from '../../resources/cards/missile-mech.jpg'
import mothership from '../../resources/cards/mothership.jpg'
import patrolMech from '../../resources/cards/patrol-mech.jpg'
import portOfCall from '../../resources/cards/port-of-call.jpg'
import ram from '../../resources/cards/ram.jpg'
import recyclingStation from '../../resources/cards/recycling-station.jpg'
import royalRedoubt from '../../resources/cards/royal-redoubt.jpg'
import scout from '../../resources/cards/scout.jpg'
import spaceStation from '../../resources/cards/space-station.jpg'
import stealthNeedle from '../../resources/cards/stealth-needle.jpg'
import supplyBot from '../../resources/cards/supply-bot.jpg'
import surveyShip from '../../resources/cards/survey-ship.jpg'
import theHive from '../../resources/cards/the-hive.jpg'
import tradeBot from '../../resources/cards/trade-bot.jpg'
import tradeEscort from '../../resources/cards/trade-escort.jpg'
import tradePod from '../../resources/cards/trade-pod.jpg'
import tradingPost from '../../resources/cards/trading-post.jpg'
import viper from '../../resources/cards/viper.jpg'
import warWorld from '../../resources/cards/war-world.jpg'


export const cardImages: Record<CardName, string> = {
    'Acceptable Losses': viper,
    'Admiral Rasmusson': viper,
    'Aging Battleship': viper,
    'Alignment Bot': viper,
    'Alliance Frigate': viper,
    'Alliance Landing': viper,
    'Alliance Transport': viper,
    'Assault Pod': viper,
    'Assault Shard': viper,
    'Assur 4': viper,
    'Asteroid Mining': viper,
    'Barter World': barterWorld,
    'Battle Barge': viper,
    'Battle Blob': battleBlob,
    'Battle Bot': viper,
    'Battle Mech': battleMech,
    'Battle Pod': battlePod,
    'Battle Screecher': viper,
    'Battle Station': battleStation,
    'Bio-Captain Kalle': viper,
    'Bio-Warrior Storm': viper,
    'Biodroid Otto': viper,
    'Bioform Freeman': viper,
    'Black Hole': viper,
    'Black Market': viper,
    'Blob Alpha': viper,
    'Blob Bot': viper,
    'Blob Builder': viper,
    'Blob Carrier': blobCarrier,
    'Blob Destroyer': blobDestroyer,
    'Blob Fighter': blobFighter,
    'Blob Miner': viper,
    'Blob Overlord': viper,
    'Blob Wheel': blobWheel,
    'Blob World': blobWorld,
    'Blockade Runner': viper,
    'Bold Raid': viper,
    'Border Fort': viper,
    'Border Skirmish': viper,
    'Bounty Hunter': viper,
    'Brain World': brainWorld,
    'Breeding Site': viper,
    'Builder Bot': viper,
    'Buyer’s Market': viper,
    'CEO Shaner': viper,
    'CEO Torres': viper,
    'Capitol World': viper,
    'Captured Outpost': viper,
    'Cargo Barge': viper,
    'Cargo Boat': viper,
    'Cargo Craft': viper,
    'Cargo Launch': viper,
    'Cargo Mech': viper,
    'Cargo Pod': viper,
    'Cargo Raptor': viper,
    'Cargo Rocket': viper,
    'Central Office': centralOffice,
    'Central Station': viper,
    'Chairman Haygan': viper,
    'Chancellor Hartman': viper,
    'Cluster Scout': viper,
    'Cluster Viper': viper,
    'Coalition Fortress': viper,
    'Coalition Freighter': viper,
    'Coalition Messenger': viper,
    'Colony Seed Ship': viper,
    'Command Center': viper,
    'Command Cruiser': viper,
    'Command Shard': viper,
    'Command Ship': commandShip,
    'Commander Klik': viper,
    'Commitment to the Cause': viper,
    'Commodore Zhang': viper,
    'Confessor Morris': viper,
    'Construction Hauler': viper,
    'Conversion Yard': viper,
    'Convoy Bot': viper,
    'Cunning Captain': viper,
    'Customs Frigate': viper,
    'Data Priest Kaufman': viper,
    'Death World': viper,
    'Defense Bot': viper,
    'Defense Center': defenseCenter,
    'Defense System': viper,
    'Defy the Empire | Rules (Defy the Empire)': viper,
    'Destroyer Bot': viper,
    'Dimensional Horror | Rules (Dimensional Horror)': viper,
    'Diplomatic Shuttle': viper,
    'Doctor Clark': viper,
    'Early Recruitment': viper,
    'Embassy Base': viper,
    'Embassy Transport': viper,
    'Embassy Yacht': embassyYacht,
    'Emergency Repairs': viper,
    'Emperor\'s Dreadnaught': viper,
    'Energy Shield': viper,
    'Enforcer Mech': viper,
    'Entrenched Loyalties': viper,
    'Escort Viper': viper,
    'Exchange Point': viper,
    'Factory World': viper,
    'Farm Ship': viper,
    'Federal Transport': viper,
    'Federation Battleship': viper,
    'Federation Cruiser': viper,
    'Federation Scout': viper,
    'Federation Shipyard': viper,
    'Federation Shuttle': federationShuttle,
    'Fighter Base': viper,
    'Fighter Pod': viper,
    'Flare Mining': viper,
    'Fleet HQ': fleetHq,
    'Fleeting Opportunities': viper,
    'Fortress Oblivion': viper,
    'Frantic Preparations': viper,
    'Freight Hauler': viper,
    'Freight Raft': viper,
    'Frontier Expedition': viper,
    'Frontier Ferry': viper,
    'Frontier Fleet': viper,
    'Frontier Hawk': viper,
    'Frontier Runner': viper,
    'Frontier Station': viper,
    'Frontier Tug': viper,
    'Fusion Bot': viper,
    'Galactic Summit': viper,
    'Heavy Cruiser': viper,
    'Hidden Base': viper,
    'High Admiral Jochum | Rules (Splinter Abilities)': viper,
    'High Admiral Shaner': viper,
    'High Priest Lyle': viper,
    'Hive Lord': viper,
    'Hive Queen': viper,
    'Imperial Defender': viper,
    'Imperial Fighter': imperialFighter,
    'Imperial Flagship': viper,
    'Imperial Frigate': imperialFrigate,
    'Imperial Palace': viper,
    'Imperial Scout': viper,
    'Imperial Smuggler': viper,
    'Imperial Talon': viper,
    'Imperial Trader': viper,
    'Imperial Viper': viper,
    'Industrial Upgrade': viper,
    'Infested Moon': viper,
    'Integration Port': viper,
    'Ion Station': viper,
    'Jamming Terminal': viper,
    'Laser Drone': viper,
    'Light Cruiser': viper,
    'Long Hauler': viper,
    'Lookout Post': viper,
    'Lost Dreadnaught': viper,
    'Loyal Colony': viper,
    'Lunar Landing': viper,
    'Machine Base': machineBase,
    'Maximum Warp': viper,
    'Mech Battleship': viper,
    'Mech Command Ship': viper,
    'Mech Cruiser': viper,
    'Mech Fortress': viper,
    'Mech World': mechWorld,
    'Mech Wurm': viper,
    'Mega Mech': viper,
    'Merc Battlecruiser': viper,
    'Merc Cruiser': viper,
    'Mercenary Garrison': viper,
    'Midgate Station': viper,
    'Mining Mech': viper,
    'Missile Bot': missileBot,
    'Missile Launcher': viper,
    'Missile Mech': missileMech,
    'Missile Silo': viper,
    'Mobile Market': viper,
    'Moonwurm Hatchling': viper,
    'Mutant Drone | Pod Token': viper,
    'Nanobot Swarm': viper,
    'Naval Yard': viper,
    'Needle Lancer': viper,
    'Nemesis Beast | Rules (Nemesis Beast)': viper,
    'Nesting Ground': viper,
    'Neural Nexus': viper,
    'Operations Center': viper,
    'Operations Platform': viper,
    'Orbital Crane': viper,
    'Orbital Gun Platform': viper,
    'Orbital Platform': viper,
    'Orbital Shuttle': viper,
    'Outland Station': viper,
    'Pact Manager Scott': viper,
    'Pact Pod': viper,
    'Pact Searcher Sheldon': viper,
    'Pact Warship': viper,
    'Parks Station': viper,
    'Patience Rewarded': viper,
    'Patrol Boat': viper,
    'Patrol Bot': viper,
    'Patrol Cutter ': viper,
    'Patrol Mech': patrolMech,
    'Picking Sides': viper,
    'Plague Pod': viper,
    'Plasma Bot': viper,
    'Plasma Vent': viper,
    'Political Maneuver': viper,
    'Port Cutter': viper,
    'Port of Call': portOfCall,
    'Powerful Backing': viper,
    'Probe Bot': viper,
    'Prolonged Conflict': viper,
    'Ram Pilot': viper,
    'Rapid Construction': viper,
    'Rapid Deployment': viper,
    'Ready Reserves': viper,
    'Reclamation Station': viper,
    'Recon Mission': viper,
    'Recon Shard': viper,
    'Recovery Mech': viper,
    'Recruiting Drive': viper,
    'Recycle Bot': viper,
    'Recycling Station': recyclingStation,
    'Repair Bot': viper,
    'Repair Mech': viper,
    'Rise to Power': viper,
    'Royal Redoubt': royalRedoubt,
    'Rushed Defenses': viper,
    'Ruthless Efficiency': viper,
    'Salvage Drone': viper,
    'Salvage Operation': viper,
    'Salvage Shard': viper,
    'Sapphire City Base': viper,
    'Scavenger Bot': viper,
    'Scout Bot': viper,
    'Scrap Factory': viper,
    'Secret Outpost': viper,
    'Security Craft': viper,
    'Siege Fortress': viper,
    'Smuggling Run': viper,
    'Solar Skiff': viper,
    'Space Station': spaceStation,
    'Spawning Wurm': viper,
    'Special Ops Director': viper,
    'Spike Cluster': viper,
    'Spike Colony': viper,
    'Spike Pod': viper,
    'Star Barge': viper,
    'Star Fortress': viper,
    'Starbase Omega': viper,
    'Stealth Needle': stealthNeedle,
    'Stealth Tower': viper,
    'Stellar Falcon': viper,
    'Stellar Link': viper,
    'Stellar Ray': viper,
    'Stellar Reef': viper,
    'Storage Silo': viper,
    'Strategist Thompson': viper,
    'Summit Site': viper,
    'Super Carrier': viper,
    'Super Freighter': viper,
    'Supply Bot': supplyBot,
    'Supply Depot': viper,
    'Supply Run': viper,
    'Surprise Assault': viper,
    'Survey Ship': surveyShip,
    'Swarm Cell': viper,
    'Swarm Cluster': viper,
    'Swarm Colony': viper,
    'Swarming Point': viper,
    'Tactical Maneuver': viper,
    'Tanker Mech': viper,
    'Templar Brehmer': viper,
    'Temple Guardian': viper,
    'The Ark': viper,
    'The Armory': viper,
    'The Citadel': viper,
    'The Colossus': viper,
    'The Hive': theHive,
    'The Incinerator': viper,
    'The Oracle': viper,
    'The Wrecker': viper,
    'Total War': viper,
    'Tractor Beam': viper,
    'Trade Bot': tradeBot,
    'Trade Envoy': viper,
    'Trade Escort': tradeEscort,
    'Trade Hauler': viper,
    'Trade Hive': viper,
    'Trade Mission': viper,
    'Trade Pod': tradePod,
    'Trade Raft': viper,
    'Trade Star': viper,
    'Trade Wheel': viper,
    'Trading Colony': viper,
    'Trading Post': tradingPost,
    'Transit Nexus': viper,
    'Transport Shard': viper,
    'Tribute Transport': viper,
    'Triumphant Return': viper,
    'Two-Pronged Attack': viper,
    'Union Cluster': viper,
    'Union Stronghold': viper,
    'Unity Fighter': viper,
    'Unity Station': viper,
    'Unity Warcraft | Rules (Part 2 of 3)': viper,
    'Unlikely Alliance': viper,
    'Valken’s Enterprise | Coalition Stronghold': viper,
    'Veteran Pilots': viper,
    'Viper Bot': viper,
    'War Elder': viper,
    'War Kite': viper,
    'War Mech': viper,
    'War World': warWorld,
    'Warning Beacon': viper,
    'Warp Jump': viper,
    'Warpgate Cruiser': viper,
    'Warpgate Nexus': viper,
    'Warrior Drone | Pod Token': viper,
    'Warrior Pod': viper,
    'Welder Drone': viper,
    'Wild Gambit': viper,
    'Worker Drone | Pod Token': viper,
    'Young Queen | Pod Token': viper,
    Ally: viper,
    Arcadia: viper,
    Armada: viper,
    Arsenal: viper,
    Assimilator: viper,
    Battlecruiser: battlecruiser,
    Bioformer: viper,
    Bombardment: viper,
    Brooder: viper,
    Burrower: viper,
    Colonize: viper,
    Comet: viper,
    Convert: viper,
    Converter: viper,
    Corsair: viper,
    Corvette: corvette,
    Crusher: viper,
    Cutter: cutter,
    Defend: viper,
    Demolisher: viper,
    Diversify: viper,
    Dominate: viper,
    Dreadnaught: dreadnaught,
    Exploration: viper,
    Explorer: explorer,
    Exterminate: viper,
    Falcon: viper,
    Flagship: flagship,
    Freighter: freighter,
    Gateship: viper,
    Guidance: viper,
    Gunship: viper,
    Hammerhead: viper,
    Hellfire: viper,
    Influence: viper,
    Junkyard: junkyard,
    Knightstar: viper,
    Lancer: viper,
    Laser: viper,
    Leviathan: viper,
    Megahauler: viper,
    Meganaut: viper,
    Mobilization: viper,
    Monopolize: viper,
    Moonwurm: viper,
    Mothership: mothership,
    Obliterator: viper,
    Parasite: viper,
    Peacekeeper: viper,
    Predator: viper,
    Processing: viper,
    Protopod: viper,
    Pulverizer: viper,
    Quasar: viper,
    Ram: ram,
    Ranger: viper,
    Ravager: viper,
    Ripper: viper,
    Rule: viper,
    Scout: scout,
    Screecher: viper,
    Sentinel: viper,
    Shield: viper,
    Starmarket: viper,
    Stealth: viper,
    Stinger: viper,
    Superflare: viper,
    Supernova: viper,
    Swarmer: viper,
    Swarmling: viper,
    Unite: viper,
    Viper: viper,
    Voyager: viper,
    Warp: viper,
    Wormhole: viper
}
